### ISSUE TITLE
missing parameter 'noise_source_time_functions' in the DATA/Par_file template

### ISSUE THREAD

**Issue by Raylhu004** [geodynamics/specfem2d#1062]
Dear developer,

A missing parameter 'noise_source_time_function' needs to be added behind 'ACOUSTIC FORCING' (Line 116)

![image](https://user-images.githubusercontent.com/53256074/82005377-c9e9eb00-9697-11ea-94d9-12c212b148d7.png)

![image](https://user-images.githubusercontent.com/53256074/82005520-2a792800-9698-11ea-8eb1-32e35e176376.png)

**Comment by danielpeter** [comment]
this has been added in commit 86b2c2af7cab00ff90ef59fcbdda8a30675b72e8
