### ISSUE TITLE
GPU Mode with coupled elastic/acoustic simulations

### ISSUE THREAD

**Issue by pasansherath** [geodynamics/specfem2d#1064]
Hi,

I have been trying to run a simulation using GPU mode to reduce the run-time of the simulation. When I use GPU mode in such a simulation, I get a warning **"Warning: Coupled elastic/fluid simulation has only valid velocity seismograms in elastic domain for GPU simulation"**. I noticed that the seismograms have zero amplitudes throughout the simulation.

Is this a current limitation in SPECFEM2D or is there a workaround to get this to work?

Thanks very much.

**Comment by danielpeter** [comment]
yes, when running on GPUs the seismogram output is still limited. for receivers in elastic domains, it is restricted to displacement/velocity/acceleration outputs, for receivers in acoustic domains, it only outputs pressure traces. 

so depending on where your receivers are and the choice of seismogram types in Par_file, some traces might just have a zero output. for example, if you need velocity traces for acoustic receivers, you would need to run simulations on CPU only.

**Comment by pasansherath** [comment]
Thanks very much @danielpeter  for the explanation.
