### ISSUE TITLE
ifort: command line remark #10148: option '-vec-report0' not supported

### ISSUE THREAD

**Issue by mlin26** [geodynamics/specfem2d#1066]
Hi,

I tried to compile specfem2d on the cluster using:

**./configure CC=icc FC=ifort**
**make**

But it shows some errors:
**ifort: command line remark #10148: option '-vec-report0' not supported**

The intel-mkl I use is **'intel-mkl/2018.2.199'**.

Could you tell me how I can solve the problem?

Thanks,
ML

**Comment by danielpeter** [comment]
right, to mute the optimization report "-vec-report0" is old and could be replaced by "-qopt-report0 -qopt-report-phase=vec" for ifort versions >=15.0.

how come you still have it in your compiler flags? it has been removed a while ago. maybe update your SPECFEM2D version and check again, the devel branch will give you the most recent version. 

(note to myself, we probably should update the master and release package...)
