### ISSUE TITLE
failed to make when setting NGLLX=4 

### ISSUE THREAD

**Issue by RAYLHU** [geodynamics/specfem2d#1067]
Hi,
the program failed to make after I set NGLLX=4 in 'specfem2d/setup/constants.h'. The error is as follows.

![image](https://user-images.githubusercontent.com/36942267/85642274-9d2be900-b6c3-11ea-9a3e-87b69e5eb3ea.png)

**Comment by danielpeter** [comment]
please remove `-Werror` from your compilation flags. 

these are in principle warnings, but with `-Werror` become compilation errors and you won't be able to compile the code. you can disregard these warnings then, those code lines will only be executed for NGLLX = 5, and simulations should run just fine with an NGLLX = 4 setting.

**Comment by RAYLHU** [comment]
Noted with thanks. The problem can also be solved by deleting these x(i, j) and z(i, j) in the error message.
