### ISSUE TITLE
failed to run he forward modeling when set NO_BACKWARD_RECONSTRUCTION='true'

### ISSUE THREAD

**Issue by RAYLHU** [geodynamics/specfem2d#1069]
Hi,

The program failed to run when I set  NO_BACKWARD_RECONSTRUCTION='true'. The message is as follows:

![image](https://user-images.githubusercontent.com/36942267/85837572-c6836c80-b7ca-11ea-8403-f7c8b9e92c73.png)

 If I change to NO_BACKWARD_RECONSTRUCTION='false', It goes back to normal. 

Regards,

Ray

**Comment by danielpeter** [comment]
please check again with the latest devel version. this should have been addressed and hopefully fixed by PR #1070
