### ISSUE TITLE
Amplification Factor in SOURCE file

### ISSUE THREAD

**Issue by pasansherath** [geodynamics/specfem2d#1083]
Hi all,

I have a question regarding the amplification factor in the DATA/SOURCE file.

Suppose I am using a factor of 1.d1. Does it imply that the resulting seismograms are scaled by a factor of 10? 

Thanks

Pasan

**Comment by EtienneBachmann** [comment]
Hi Pasan,

Yes, as Specfem solves the linear wave equation, this is true for any configuration ( visco acoustic / elastic).

Etienne

**Comment by pasansherath** [comment]
Thanks for the confirmation @EtienneBachmann

**Comment by brioglade** [comment]
hi,this means that M0 is not  seismic moment???
