### ISSUE TITLE
Gmsh_example_Stacey_MPI Question

### ISSUE THREAD

**Issue by ceeroover** [geodynamics/specfem2d#1148]
I don't get the Gmsh_example_Stacey_MPI example to work when I build the mesh from the *.geo file.

It runs smoothly when I run it with the original files or when I create the mesh files from the existing SqrCirq.msh as provided in the example Readme with:

`python ../../../utils/Gmsh/LibGmsh2Specfem_convert_Gmsh_to_Specfem2D_official.py SqrCirc.msh -t F -l A -b A -r A`

but when I create the mesh file by:

`gmsh SqrCirc.geo -2 -order 2 -format msh22 -o SqrCirc.msh`

and then 

`python ../../../utils/Gmsh/LibGmsh2Specfem_convert_Gmsh_to_Specfem2D_official.py SqrCirc.msh -t F -l A -b A -r A`

the run aborts at timestep 200 (with all the same settings as before):

```
 Creating color image of size          762  x          800  for time step          200
 drawing scalar image of the forward wavefield pressure...
 Color image maximum amplitude =    5.8021328613916545E+034
 Warning: failed creating color image, maximum value of amplitude in image color is invalid
 amplitude max =    5.8021328613916545E+034  with threshold at    1.0000000000000001E+025
 Please check your simulation setup...
 code became unstable and blew up (image_color_data)
 Error detected, aborting MPI... proc            0
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 30.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
```
par and source files are original from the example
I'm using gmsh 4.8.4

I have just tried the examples so far, so I don't really understand what I could do differently or what is causing the error message.

**Comment by ceeroover** [comment]
Looks like the mesh just wasn't fine enough on the newly created mesh file.

**Comment by DoctorTall** [comment]
Hello, I have met the same problem. Have you found the solution?
