### ISSUE TITLE
Clarification on the Meanings of Hessian1_kernel and Hessian2_kernel in APPROXIMATE_HESS_KL Mode

### ISSUE THREAD

**Issue by zhangchang271** [geodynamics/specfem2d#1235]
### Description

Hello,

I am currently using the SPECFEM2D, and I have enabled the `APPROXIMATE_HESS_KL` mode during my simulations. After computing the adjoint sources, I noticed that two Hessian Kernels are generated: `Hessian1_kernel` and `Hessian2_kernel`. However, the documentation for SPECFEM2D does not provide detailed descriptions of these kernels, and I am unsure about their specific meanings.

From what I can gather based on the SPECFEM3D  documentation in the "Summing kernels" section (section 8.2.1), there typically appears to be only one kernel discussed. After plotting these two kernels, it seems that `Hessian1_kernel` might correspond to the P-wave velocity (Vp) and `Hessian2_kernel` might correspond to the S-wave velocity (Vs), but I am unable to find any kernel for the density parameter.

Could you please help clarify the following:
1. What exactly do `Hessian1_kernel` and `Hessian2_kernel` represent in the context of APPROXIMATE_HESS_KL?
2. Should there be a kernel representing the density, and if so, how can I generate or locate it?

Thank you for your assistance and for the ongoing development of this powerful tool.

### Affected SPECFEM2D version

e70c9c88e5f0a1edc64870c514ef52d08e5d1ef0

### Your software and hardware environment

Intel(R) Fortran Intel(R) 64 Compiler Classic for applications running on Intel(R) 64, Version 2021.12.0 Build 20240222_000000;Ubuntu22.04

### Reproduction steps

```bash
1. set APPROXIMATE_HESS_KL             = .true. # outputs approximate Hessian for preconditioning
2. run adjoint simulation
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Linux

**Comment by armandoespindola** [comment]
Hi trinitite271,

About the Hessian approximation, the first approximation [Hessian1](https://github.com/SPECFEM/specfem2d/blob/1ddef3d47d4aac6781340f58f6d22536a195ad2d/src/specfem2D/compute_kernels.f90#L786) only considers the forward seismic field, and the second approximation [Hessian2](https://github.com/SPECFEM/specfem2d/blob/1ddef3d47d4aac6781340f58f6d22536a195ad2d/src/specfem2D/compute_kernels.f90#L788) considers the forward and adjoint field.

A
