### ISSUE TITLE
Results from Gaussian, its first and second (Ricker) derivatives are same

### ISSUE THREAD

**Issue by samyog111** [geodynamics/specfem2d#1238]
### Description

I am  currently working on a 1D two-layered seismic model using SPECfem2D. I have confirmed that all parameters are correctly set in my model. However, my results do not match with the expected outcomes from FLAC analyses. It seems the issue arises from the source not being evenly applied across all points beneath the 1D model in SPECfem. I attempted to address this by applying the Ricker wavelet throughout the lower surface in the model, setting the initial field option to true, but this approach has not been successful (as it is applying the source wavelet in the top surface of the model). Could you please advise on the correct method to uniformly apply the source wavelet below the model?

### Affected SPECFEM2D version

specfem2D 2021

### Your software and hardware environment

frisco.chpc.utah.edu

### Reproduction steps

```bash
1. Go to '...'
2. Change settings '....'
3. Use data files '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by danielpeter** [comment]
could explain a bit more what you mean by: 

> ".. source not being evenly applied across all points beneath the 1D model in SPECfem. .." 

and add your `Par_file` setup and the generated console output (or output files) for reproducing this example?
