### ISSUE TITLE
remove copyrighted routines from attenuation_compute_param.c

### ISSUE THREAD

**Issue by QuLogic** [geodynamics/specfem2d#13]
This file appears to contain code from Numerical Recipes. NR code is not license compatible with open source code. It should be replaced.

**Comment by komatits** [comment]
The new (open source) routines work fine and have been tested and used successfully for a few months, thus in a few months (around this summer 2015 or so) we can permanently get rid of the old ones.

**Comment by komatits** [comment]
Almost done, will finish it and will remove them in the next two weeks; my group is almost done testing the new version (which is also more accurate, and ensures positivity of the coefficients found, which the old one did not).

**Comment by komatits** [comment]
Done.
