### ISSUE TITLE
suggestions for refactoring write_seismograms

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem2d#166]
To improve consistency between solver packages, I recently made some changes to write_seismograms.f90.  Looking forward, there are still some aspects that could be improved, I think. 

- In the 2D code, the 'seismotype' parameter determines whether pressure, displacement, velocity, or acceleration traces are output. In the 3D code, output type depends only on the material properties of the element in which a receiver is located.   Changing to the way things are done in 2D by removing the 'seismotype' parameter could not only improve consistency between packages, it could also greatly improve the appearance of the code in places. Other than requiring a change to the parameter file format, I can't think offhand of any downsides.

- Arrays used to hold seismic data have misleading names. For example, arrays with 'x' in the variable name sometimes hold pressure data or y-component data instead of x-component data.

**Comment by komatits** [comment]
Done by @rmodrak
