### ISSUE TITLE
frequency limits ?

### ISSUE THREAD

**Issue by ClaraCL** [geodynamics/specfem2d#222]
Hello,
I am trying to do a high frequency acoustic simulation in a simple homogenous flat medium.
When I try to refine the mesh from elements of size 20m x 20m to elements of size 10m x 10m I get a core error.I have made sure I am respecting the CFL condition. Is there a frequency limit ?

**Comment by komatits** [comment]
Hello,

Thanks! No, there is no frequency limit (only the amount of memory available on your machine).

**Comment by ClaraCL** [comment]
Hello, 
 I found where the problem is, but I haven't found the problem.
It is in : call compute_vector_whole_medium

So, with the jpeg option to false, it nevers calls this subroutine and it doesn't crash.
If I find the bug in call compute_vector_whole_medium    I'll let you know. 

By the way, is there an option to keep the receivers at the depth exactly as they are read from the STATIONS file ?  That is, an option to do something like what is done in specfem3d in the 
constants.h file,  where you can set_receivers_true_depth=.true.

**Comment by komatits** [comment]
Hello,

Thanks! If you email me your Par_file and SOURCE file I can have a look 
and locate and fix the bug.

Regarding the receivers, in the 2D code they are always located at their 
true position read from the input file; it is only in the 3D code that 
we have a (rarely used) option to use the closest grid point instead to 
reduce the cost if the user wants to.

Best wishes,
Dimitri.

On 02/26/2015 11:26 PM, ClaraCL wrote:
> Hello,
> I found where the problem is, but I haven't found the problem.
> It is in : call compute_vector_whole_medium
>
> So, with the jpeg option to false, it nevers calls this subroutine and
> it doesn't crash.
> If I find the bug in call compute_vector_whole_medium I'll let you know.
>
> By the way, is there an option to keep the receivers at the depth
> exactly as they are read from the STATIONS file ? That is, an option to
> do something like what is done in specfem3d in the
> constants.h file, where you can set_receivers_true_depth=.true.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/222#issuecomment-76288155>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
