### ISSUE TITLE
make external model parameters and procedures consistent with 3D packages

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem2d#232]
In an upcoming pull request, `assign_external_model` and `READ_EXTERNEL_SEP_FILE` will be replaced with the following Par_file entry
```
# available models
#   default: model described by nbmodels (see below)
#   ascii: reads model from ascii database file
#   binary: reads model from binary databse files
#   external: calls define_external_model subroutine
#   legacy: reads model from 'model_velocity.dat_input'
MODEL                           = default
```
Besides making the Par_file and external model parameters and procedures consistent with the 3D packages, these changes also help with issues #231, #223, #79.

Changes have been validated using an elastic inversion test case.

Note: EXAMPLES/ Par_files still need to be updated.  After the current changes are accepted, I will go ahead and run `make external model procedure consistent with 3D packages.py`,  commit the results, and submit another pull request.

**Comment by rmodrak** [comment]
Carried out in pull request #233.  Perhaps it would be good to leave this issue up for a few days as a courtesy to users who may need to update Par_file s?

**Comment by komatits** [comment]
Thanks! Very useful.

Dimitri.

On 03/07/2015 06:50 AM, rmodrak wrote:
> In an upcoming pull request, |assign_external_model| and
> |READ_EXTERNEL_SEP_FILE| will be replaced with the following Par_file entry
>
> |# available models
> #   default: model described by nbmodels (see below)
> #   ascii: reads model from ascii database file
> #   binary: reads model from binary databse files
> #   external: calls define_external_model subroutine
> #   legacy: reads model from 'model_velocity.dat_input'
> MODEL                           = default
> |
>
> Besides making the Par_file and external model parameters and procedures
> consistent with the 3D packages, these changes also help with issues
> #231 <https://github.com/geodynamics/specfem2d/issues/231>, #223
> <https://github.com/geodynamics/specfem2d/issues/223>, #79
> <https://github.com/geodynamics/specfem2d/issues/79>.
>
> Changes have been validated using an elastic inversion test case.
>
> Note: EXAMPLES/ Par_files still need to be updated. After the current
> changes are accepted, I will go ahead and run |make external model
> procedure consistent with 3D packages.py|, commit the results, and
> submit another pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/232>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Hi Ryan,

Could you commit that validation test (as well as the related scripts) 
to directory "EXAMPLES"?
That would be very useful. Many users are asking for an example showing 
how to perform inversion i.e. how to iterate, not only computing kernels.

Thanks,
Dimitri.

On 03/07/2015 06:50 AM, rmodrak wrote:
> Changes have been validated using an elastic inversion test case.


-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
Hi Dimitri,

The short answer is, it is almost impossible to implement inversion the framework EXAMPLES/.  I spent over a year trying.  There is just not enough flexibility.  After the fact, I found that Carl had tried a similar approach and gotten a similar result.

To explain myself better though, let me write to you and Etienne in a longer email.

Until then,
Ryan

**Comment by rmodrak** [comment]
As a result of the above changes, there are a few places the user manual needs to be updated.  Right now, I'm having trouble getting the tex file to compile, but I hope to resolve this shortly.

**Comment by rmodrak** [comment]
Okay, I've updated relevant text in the user manual.  If it's alright, I'll go ahead and close this issue.  Thanks, Ryan

**Comment by komatits** [comment]
Thanks!
Dimitri

On 03/22/2015 11:39 PM, rmodrak wrote:
> Okay, I've updated relevant text in the user manual. If it's alright,
> I'll go ahead and close this issue. Thanks, Ryan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/232#issuecomment-84721793>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
