### ISSUE TITLE
problem with acoustic/elastic coupling when using external model?

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem2d#240]
In the following seismic exploration example, it appears acoustic and elastic regions are correctly defined and recognized by the solver.  The wavefield originates in the upper acoustic layer and propagates downward.  Strangely, the wavefield is completely reflected at the acoustic/elastic boundary, and never makes it into the elastic region:
![image0001300](https://cloud.githubusercontent.com/assets/4483402/6587186/933326ae-c757-11e4-8566-2189f87d4966.jpg)

**Comment by rmodrak** [comment]
The Par_file used for the above simulation is given below:

```

title                           = marmousi

AXISYM                          = .false.


SIMULATION_TYPE                 =3
NOISE_TOMOGRAPHY                = 0   
SAVE_FORWARD                    =.false.


nproc                           = 1              
partitioning_method             = 3              

ngnod                           = 9              
initialfield                    = .false.        
add_Bielak_conditions           = .false.        

MODEL                           = ascii

ATTENUATION_VISCOELASTIC_SOLID  = .false.        
ATTENUATION_PORO_FLUID_PART     = .false.        
Q0                              =  1             
freq0                           =  10            
p_sv                            = .true.


nt                              = 7500           
deltat                          = 9.0d-4         
USER_T0                         = 0.0d0          
time_stepping_scheme            = 1   

ACOUSTIC_FORCING                = .false.


NSOURCES                        = 1              
force_normal_to_surface         = .false.        


N_SLS                           = 2                      
f0_attenuation                  = 5.196152422706633      
READ_VELOCITIES_AT_f0           = .false.


seismotype                      = 1              
USE_TRICK_FOR_BETTER_PRESSURE   = .true.
NSTEP_BETWEEN_OUTPUT_SEISMOS    = 5000000        
save_ASCII_seismograms          = .false.         
save_binary_seismograms_single  = .true.         
save_binary_seismograms_double  = .false.        
SU_FORMAT                       = .true.        
subsamp_seismos                 = 1              
use_existing_STATIONS          = .false.
nreceiversets                   = 1              
anglerec                        = 0.d0           
rec_normal_to_surface           = .false.        
save_ASCII_kernels              = .true.


nrec                            =  500
xdeb                            =   50.          
zdeb                            = 3490.          
xfin                            = 9150.          
zfin                            = 3490.          
enreg_surf_same_vertical        = .false.        


NSTEP_BETWEEN_OUTPUT_INFO      = 200            
NSTEP_BETWEEN_OUTPUT_IMAGES     = 100            
cutsnaps                        = 1.             


output_color_image              = .true.
imagetype_JPEG                  = 3              
factor_subsample_image          = 1              
USE_CONSTANT_MAX_AMPLITUDE      = .false.
CONSTANT_MAX_AMPLITUDE_TO_USE   = 1.17d4
POWER_DISPLAY_COLOR             = 0.30d0         
DRAW_SOURCES_AND_RECEIVERS      = .true.         
DRAW_WATER_IN_BLUE              = .true.         
USE_SNAPSHOT_NUMBER_IN_FILENAME = .false.        


output_postscript_snapshot      = .false.        
imagetype_postscript            = 1              
meshvect                        = .true.         
modelvect                       = .false.        
boundvect                       = .true.         
interpol                        = .true.         
pointsdisp                      = 6              
subsamp_postscript              = 1              
sizemax_arrows                  = 1.d0           
US_LETTER                       = .false.        


NSTEP_BETWEEN_OUTPUT_WAVE_DUMPS = 100            
output_wavefield_dumps          = .false.        
imagetype_wavefield_dumps       = 1              
use_binary_for_wavefield_dumps  = .false.        

output_grid_Gnuplot             = .true.        
output_grid_ASCII               = .false.        
output_energy                   = .false.        


nbmodels                        = 1              






1 1 2.7d3 2.60d3 1.5d3 0 0 9999 9999 0 0 0 0 0 0
2 1 2.7d3 9.53d3 5.5d3 0 0 9999 9999 0 0 0 0 0 0


read_external_mesh              = .false.


PML_BOUNDARY_CONDITIONS         = .false.
NELEM_PML_THICKNESS             = 3
ROTATE_PML_ACTIVATE             = .false.
ROTATE_PML_ANGLE                = 30.
STACEY_ABSORBING_CONDITIONS     = .true.
ADD_SPRING_TO_STACEY            = .false.


ADD_PERIODIC_CONDITIONS         = .false.


PERIODIC_HORIZ_DIST             = 0.3597d0


PERIODIC_DETECT_TOL             = 3.3334d-6

GPU_MODE                        = .false.





mesh_file                       = ./DATA/Mesh_canyon/canyon_mesh_file   
nodes_coords_file               = ./DATA/Mesh_canyon/canyon_nodes_coords_file   
materials_file                  = ./DATA/Mesh_canyon/canyon_materials_file   
free_surface_file               = ./DATA/Mesh_canyon/canyon_free_surface_file   
absorbing_surface_file          = ./DATA/Mesh_canyon/canyon_absorbing_surface_file   
CPML_element_file               = Elements_CPML_list  
tangential_detection_curve_file = ./DATA/courbe_eros_nodes 





interfacesfile                  = interfaces.dat


xmin                            = 0.d0           
xmax                            = 9200.d0          
nx                              = 90             


absorbbottom                    = .true.
absorbright                     = .true.
absorbtop                       = .true.
absorbleft                      = .true.


nbregions                       = 1              
1  90  1 30 1

```

**Comment by komatits** [comment]
People who may know how to fix that are Alexis @bottero , Zhinan @xiezhinan , Ryan @rmodrak .

**Comment by rmodrak** [comment]
Hi all, 

I understand what's going on now.  When using an external fluid/solid model, is not enough to make sure that all GLL points within a given element are consistent, that each element has a consistent acoustic or elastic type.  In addition, the type of a given element, whether acoustic or elastic, must match the type defined via ``nbmodels`` for the region in which the element lies.  This was unexpected for me because, when using an external model, ``nbmodels`` values are ignored in all other respects.  After looking at the code though, it makes sense.  

Thanks for looking at this,
Ryan

**Comment by komatits** [comment]
Hi Ryan,

Yes, this comes from the fact that flags such as acoustic(), elastic(), 
poroelastic() are assigned early in the code, before calling 
define_external_model, thus they are assigned based on the type defined 
via |nbmodels| for the region in which the element lies.

(not sure how easy it would be to change that; changing it would be a 
good idea if it is not too difficult to do)

In principle the code checks that and stops if it is not the case (at 
least in define_external_model_dummy() I am pretty sure I put a test 
like that: if the element is supposed to be acoustic for instance but 
define_external_model() tries to assign it a non-zero S wave velocity 
then the code stops with an error message.

Any idea why the stop statement was not triggered in your case?
(we should make sure it is, otherwise as you say users will get wrong 
results).

Thanks,
Dimitri.

On 03/23/2015 12:14 AM, rmodrak wrote:
> Hi all,
>
> I understand what's going on now. When using an external fluid/solid
> model, is not enough to make sure that all GLL points within a given
> element are consistent, that each element has a consistent acoustic or
> elastic type. In addition, the type of a given element, whether acoustic
> or elastic, must match the type defined via |nbmodels| for the region in
> which the element lies. This was unexpected for me because, when using
> an external model, |nbmodels| values are ignored in all other respects.
> After looking at the code though, it makes sense.
>
> Thanks for looking at this,
> Ryan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/240#issuecomment-84731075>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Hi Ryan,

Thanks! My group will try to have a look in the next few weeks.
Thanks again,

Dimitri.

On 10/03/2016 20:14, rmodrak wrote:
> Hi Dimitri,
>
> I looked up this old issue because another student asked me about it
> today. I'm sorry I missed your response amid the other SPECFEM2D email
> updates.
>
> Just for the record, I do remember looking into whether it would be
> straightforward to obtain material labels from the external model,
> rather than |nbmodels|. It may be just because I am unfamiliar with
> those routines, but it seemed quite complicated and difficult on account
> of special treatment required for boundaries and corners between elements.
>
> Regarding the stop statement, I believe that was only triggered if both
> acoustic and elastic points are found within the same element (i.e.
> inconsistency within an element), not if an entire element is flagged
> incorrectly.
>
> Ryan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/240#issuecomment-195005805>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
Sorry again for the delay.  I don't think it's urgent,  we are able to work
around.  I just wanted to post something for the record.
