### ISSUE TITLE
use CUSTOM_REAL precision for external model arrays

### ISSUE THREAD

**Issue by rmodrak** [geodynamics/specfem2d#255]
Both SPECFEM3D and 3D_GLOBE read external models into CUSTOM_REAL arrays.  SPECFEM2D uses double precision arrays.  

- Changing from double precision to CUSTOM_REAL would remove the need for a lot of messy type casting statements.  

- The difference seems to be nothing more than a historical quirk, having to do with the attenuation routines.

- With CUSTOM_REAL arrays, the SPECFEM2D postprocessing routines could be made to work the same as 3D and 3D_GLOBE postprocessing routines.

- Double precision make little sense given that, historically, external models have almost always been read from ASCII files.

If it's alright with Dimitri, Etienne, and everyone else,  I'll go ahead and make this change.

**Comment by EtienneBachmann** [comment]
Very good idea, I totally agree with this change.

**Comment by komatits** [comment]
I also agree, very good idea.

Dimitri.

On 03/23/2015 10:21 AM, EtienneBachmann wrote:
> Very good idea, I totally agree with this change.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/255#issuecomment-84908772>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
Hi all,

Okay, I think this issue has been wrapped up.  I did a quick test and found no errors.  Thanks everyone's feedback.

Ryan

**Comment by komatits** [comment]
Thanks!
Excellent news.

Dimitri.

On 03/25/2015 02:07 AM, rmodrak wrote:
> Hi all,
>
> Okay, I think this issue has been wrapped up. I did a quick test and
> found no errors. Thanks everyone's feedback.
>
> Ryan
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/255#issuecomment-85768684>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
Incidentally, it seems the examples were broken last week on or around commit 77bb12ef6f8c3d5e6354833243903aec7a68a2ce.  I'm not sure exactly what the issue.  Once the examples are working again, I'll be sure to run them.  I hesitate to close this issue until I can run the examples and make sure everythings working properly in light of the change in precision (in particular Carl's example that uses a external model).

**Comment by komatits** [comment]
Could it be that the person who created commit 77bb12e 
<https://github.com/geodynamics/specfem2d/commit/77bb12ef6f8c3d5e6354833243903aec7a68a2ce> 
forgot to update all the Par_files accordingly (i.e. add the new 
parameter to all of them).

If so, just use my script 
specfem2d/EXAMPLES/view_all_parameter_files_to_modify_them.csh to add it 
and you should be all set.

Thanks,
Dimitri.

On 03/25/2015 02:09 AM, rmodrak wrote:
> Incidentally, it seems the examples were broken last week on or around
> commit 77bb12e
> <https://github.com/geodynamics/specfem2d/commit/77bb12ef6f8c3d5e6354833243903aec7a68a2ce>.
> I'm not sure exactly what the issue. Once the examples are working
> again, I'll be sure to run them. I hesitate to close this issue until I
> can run the examples and make sure everythings working properly in light
> of the change in precision (in particular Carl's example that uses a
> external model).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/255#issuecomment-85768896>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by rmodrak** [comment]
Yep, that sounds likely.  I'll go ahead and look into it.
