### ISSUE TITLE
Unused variables detected in latest commit

### ISSUE THREAD

**Issue by luet** [geodynamics/specfem2d#319]
I am upgrading the compiler on the slave before I generate new reference seismograms.
When compiling with gfortran 4.8.2, which is better at detected unused variables than the older version, I get:
    src/specfem2D/axisymmetric_routines.f90:252.8:
    
    use specfem_par, only: nglob_acoustic, acoustic, elastic, coord, ibool, nel
        1
    Warning: Unused module variable 'myrank' which has been explicitly imported at (1)
    src/specfem2D/axisymmetric_routines.f90:252.8:

        use specfem_par, only: nglob_acoustic, acoustic, elastic, coord, ibool, nel
            1
    Warning: Unused module variable 'nglob_acoustic' which has been explicitly imported at (1)
    make: *** [obj/axisymmetric_routines.spec.o] Error 1

You can see more details on the [buildbot run](http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/197/steps/--disable-double-precision_make/logs/stdio).

**Comment by komatits** [comment]
Hi David,

Thanks. I fixed them.

BuildBot will detect them as soon as you are done upgrading your GNU 
compiler. Thus this will not happen any more, users will be asked by 
BuildBot to fix them before accepting the pull request.

That detection of unused variables in modules is a new feature of 
gfortran 4.8.

Thanks,
Dimitri.

On 04/29/2015 11:01 PM, David Luet wrote:
> I am upgrading the compiler on the slave before I generate new reference
> seismograms.
> When compiling with gfortran 4.8.2, which is better at detected unused
> variables than the older version, I get:
> src/specfem2D/axisymmetric_routines.f90:252.8:
>
> |use specfem_par, only: nglob_acoustic, acoustic, elastic, coord, ibool, nel
>      1
> Warning: Unused module variable 'myrank' which has been explicitly imported at (1)
> src/specfem2D/axisymmetric_routines.f90:252.8:
>
>      use specfem_par, only: nglob_acoustic, acoustic, elastic, coord, ibool, nel
>          1
> Warning: Unused module variable 'nglob_acoustic' which has been explicitly imported at (1)
> make: *** [obj/axisymmetric_routines.spec.o] Error 1
> |
>
> You can see more details on the buildbot run
> <http://specfem2d-buildbot.princeton.edu/builders/specfem2d_builder/builds/197/steps/--disable-double-precision_make/logs/stdio>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/319>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr
