### ISSUE TITLE
CUDA compilation issue

### ISSUE THREAD

**Issue by EtienneBachmann** [geodynamics/specfem2d#482]
Hello everybody,

Very recently, @danielpeter made a nice contribution, involving simplification of the Makefile, and made it similar to the 3D version.
Nevertheless, I have a compilation issue with the CUDA code, at the linking phase, in both 2D and 3D code with this new implementation. I get many lines like that : 
./obj/compute_stacey_acoustic_cuda.cuda.o:(.eh_frame+0x12): undefined reference to `__gxx_personality_v0'

I succeed to get rid of this by adding a -lstdc++ flag in the CUDA_LINK flags. I had this problem on a standalone machine, and on a cluster (the tiger Princeton cluster). It seems that on another cluster (titan Princeton cluster), users don t have this error. 

I guess it s a matter of version of compiler ? To avoid compilation error I suggest to add this flag (-lstdc++) in the Makefile of the 3 specfem versions.

Thanks

Etienne

**Comment by danielpeter** [comment]
hi Etienne, sure let's just add it then... 

nvcc uses the host C++ compiler, the final SPECFEM code linkage is done however by the F90 compiler (or MPIF90 compiler, specified by the user). this might miss this -lstdc++ option. usually i find it done by default installation.

**Comment by EtienneBachmann** [comment]
Thanks!

This issue is now solved
