### ISSUE TITLE
Error using gfortran and Specfem2D (maybe also 3D)

### ISSUE THREAD

**Issue by EtienneBachmann** [geodynamics/specfem2d#531]
Hello everybody,

I d like to report an error at the execution time for a code that have been compiled with Gfortran. I guess that these errors have been introduced by @danielpeter when restructuring the code.

The error is the following: With gfortran, when routine is calling a subroutine, and both are using "use module, only :" you must be sure that all the module variables that are in the subsubroutine are also cited by the subroutine. If not, the value of the variable are dummy and cannot be changed, which will obviously generate mistakes.
An example : 

subroutine A
use module, only : X 
call B()
...
end subroutine A
  
subroutine B
use module, only Y
.....
end subroutine B

This example will generate a mistake because the value of Y is not good. To correct it, we must change :
 
subroutine A
use module, only : X, Y 
call B()
...
end subroutine A

and it will work.

This error is very vicious, because gfortran does not even provide a warning at the compilation time, and this is why @buildbot-princeton does not see it for instance. It will only appear when executing the code. Besides for ifort users, there are no errors at all when executing the code. 

For that reason, I tried one year ago to remove as much as possible the 'only' statements, as long as it does not hit the performance, and even reduce the compile time, but the program is large and many 'only' remain.

Best,

Etienne

**Comment by QuLogic** [comment]
To be honest, this sounds like a bug in your compiler version. What version are you using? Do you have an example where this fails?

**Comment by komatits** [comment]
Hi!

Yes, likely a compiler problem: the current devel version works fine here on my laptop with gfortran 4.8.4 (including timings).

Best,
Dimitri.
