### ISSUE TITLE
problem running plane wave simulations with more than one processor

### ISSUE THREAD

**Issue by nmancinelli** [geodynamics/specfem2d#550]
I am using SPECFEM2D to simulate an SV plane wave incident upon the free surface, where the Earth model is heterogeneous and is read in from a file.

I have noticed, however, that instabilities quickly develop in the wavefield when I use more than a single processor, and that the apparent number of instabilities increases with the number of processors.  I have been able to reproduce this issue on two independent systems, and the issue does not seem to be particularly sensitive to the specific 2D velocity model that I choose.

Attached are images of the wavefield and an example Par_file.

![image0000500 1proc](https://cloud.githubusercontent.com/assets/18191441/14177946/968cb072-f726-11e5-8e45-367d54bd0985.jpg)
![image0000500 2proc](https://cloud.githubusercontent.com/assets/18191441/14177954/9cdf7414-f726-11e5-9f5c-ceeda24dceac.jpg)
![image0000500 8proc](https://cloud.githubusercontent.com/assets/18191441/14177960/a112f9ac-f726-11e5-89af-de8d422b25f4.jpg)

[Par_file.txt](https://github.com/geodynamics/specfem2d/files/197751/Par_file.txt)

**Comment by komatits** [comment]
Thanks for your bug report. This bug is now fixed.
Dimitri.
