### ISSUE TITLE
Computing post-critical reflection waves with SPECFEM2D

### ISSUE THREAD

**Issue by tianzeliu** [geodynamics/specfem2d#784]
Hi There,
I was trying computing post-critical reflection waves generated by incident plane waves on solid interfaces with SPECFEM2D, and found that the program ran for extremely long time before it crashed in the end. Is it because the program cannot handle post-critical reflection, or because I set up the wrong model? I am attaching my parameter files below. Thanks.
[interfaces_simplecrust.txt](https://github.com/geodynamics/specfem2d/files/1024553/interfaces_simplecrust.txt)
[Par_file.txt](https://github.com/geodynamics/specfem2d/files/1024554/Par_file.txt)
[SOURCE.txt](https://github.com/geodynamics/specfem2d/files/1024555/SOURCE.txt)

**Comment by komatits** [comment]
Hi,
In principle it should work, my student Ronan Madec did that back in 2009 and did not notice any problem (back then).
Yes, the code can then take a while to start because it performs FFTs at each grid point to compute the initial wave field.

Best regards,
Dimitri.
