### ISSUE TITLE
in Specfem2D, only one partition of "model_velocity.dat_output" is generated in the case of MPI runs

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem2d#79]
Subject: [CIG-SEISMO] only one partition of "model_velocity.dat_output" will be generated in parallel run
Date: Mon, 12 Aug 2013 18:03:40 +0100
From: Yingzi Ying
To: cig-seismo

Dear SPECFEM Developers,

In parallel running of xspecfem2D, only one partition of "model_velocity.dat_output" will be generated.
Both mpirun and mpiexec executions have been tested.
The whole mesh can be generated in serial running.
Just a bug report.

Thanks,
Yingzi

**Comment by rmodrak** [comment]
Fixing this issue would require changing changing the filename to something like `proc***_rho_vp_vs.dat`.

As a first step, I could go ahead and make this change if you like.

**Comment by komatits** [comment]
Very good idea.
Thanks,
Dimitri.

On 03/06/2015 03:07 AM, rmodrak wrote:
> Fixing this issue would require changing changing the filename to
> something like |proc***_rho_vp_vs.dat|.
>
> As a first step, I could go ahead and make this change if you like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geodynamics/specfem2d/issues/79#issuecomment-77493771>.
>

-- 
Dimitri Komatitsch
CNRS Research Director (DR CNRS), Laboratory of Mechanics and Acoustics,
UPR 7051, Marseille, France    http://komatitsch.free.fr

**Comment by komatits** [comment]
Fixed by Ryan @rmodrak I think. Ryan, if so could you confirm and also close the issue. Thanks.

**Comment by EtienneBachmann** [comment]
With the last commit (09/092015, Adding MPI support for external model )  , this issue is now fixed.

**Comment by komatits** [comment]
Fixed (and this output file has later been suppressed).
