### ISSUE TITLE
current SPECFEM2D PMLs do not support the fluid-solid boundary not inside CPML_X_ONLY

### ISSUE THREAD

**Issue by komatits** [geodynamics/specfem2d#81]
@xiezhinan  
Dear Zhinan,

It would be really great if you could do it when you have 
time, because in the attached Par_file I had to rotate the model by 90 
degrees in order for the code to work (the model is supposed to be 
horizontal instead of vertical).

Thanks,
Dimitri.

On 26/02/2014 03:36, 谢志南 wrote:
> Dear Dimtri,
>
> We can to change to support CPML_Z_ONLY as well.
> If you want, I can do the job.
>
> Thank you so much.
> Best regards,
> Zhinan
>
>
> 2014-02-26 9:46 GMT+08:00 Dimitri Komatitsch:
>
>
>     Dear Zhinan,
>
>     When I try to put a fluid-solid boundary inside the PML in the
>     vertical direction, the code currently displays this:
>
>     PML do not support the fluid-solid boundary not inside CPML_X_ONLY.
>
>     How easy would it be to implement it in CPML_Z_ONLY as well?
>
>     (we could exclude the corners, i.e. change it to:
>
>     PML do not support the fluid-solid boundary inside CPML corners.
>
>     Could you tell me if you think this is easy to implement, or
>     difficult to implement?
>
>     Thank you very much,
>     Best regards,
>
>     Dimitri.

**Comment by komatits** [comment]
@xiezhinan will do that, or has already done it. I will check with him.

**Comment by xiezhinan** [comment]
It has already been done, Sir.

**Comment by komatits** [comment]
Thanks a lot!
